name: "Update-associate-number"
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
jobs:
  update-associates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      
      - name: Setup dependencies
        uses: r-lib/actions/setup-renv@v2
        
      - name: Update associates data
        env: 
          ASSOCITRACK_PASSWORD: ${{ secrets.ASSOCIATRACK_PASSWORD }} 
        run:
          R -e 'renv::run("R/get_associate_number.R")'
